project_id = "tljsbmpglwmzyaoxsqyj"

[functions.send-share-email]
verify_jwt = true

[functions.send-contact-reply]
verify_jwt = false

[functions.send-bulk-email]
verify_jwt = false

[functions.generate-figure-from-reference]
verify_jwt = true

[functions.generate-icon-from-reference]
verify_jwt = true
