project_id = "tljsbmpglwmzyaoxsqyj"

[functions.send-announcement]
verify_jwt = true

[functions.inflate-community-metrics]
verify_jwt = true

[functions.rate-limited-login]
verify_jwt = false

[functions.subscribe-newsletter]
verify_jwt = false

[functions.send-share-email]
verify_jwt = true

[functions.send-contact-reply]
verify_jwt = false

[functions.send-bulk-email]
verify_jwt = true

[functions.verify-captcha]
verify_jwt = false

[functions.generate-figure-from-reference]
verify_jwt = true
timeout = 180

[functions.generate-icon-from-reference]
verify_jwt = true

[functions.generate-powerpoint]
verify_jwt = true
timeout = 180
